package com.hits20radio.online
import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.os.Bundle;import android.widget.*;import androidx.activity.ComponentActivity;import androidx.core.app.ActivityCompat;import androidx.core.content.ContextCompat;import androidx.media3.common.MediaItem;import androidx.media3.common.Player;import androidx.media3.session.*;import com.google.common.util.concurrent.ListenableFuture
class MainActivity:ComponentActivity(){companion object{const val RADIO="https://stream.radiosmundiales.com:8692/stream"};lateinit var f:ListenableFuture<MediaController>;var c:MediaController?=null;lateinit var s:AudioSpectrumView;lateinit var b:Button;lateinit var st:TextView
override fun onCreate(x:Bundle?){super.onCreate(x);setContentView(R.layout.activity_main);s=findViewById(R.id.spectrum);b=findViewById(R.id.play);st=findViewById(R.id.status)
if(ContextCompat.checkSelfPermission(this,Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)ActivityCompat.requestPermissions(this,arrayOf(Manifest.permission.RECORD_AUDIO),2)
val t=SessionToken(this,ComponentName(this,PlaybackService::class.java));f=MediaController.Builder(this,t).buildAsync();f.addListener({c=f.get();c?.addListener(object:Player.Listener{override fun onIsPlayingChanged(q:Boolean){b.text=if(q)"❚❚ PAUSAR" else "▶ ESCUCHAR HITS20";st.text=if(q)"● TRANSMITIENDO EN VIVO" else "RADIO PAUSADA";if(q)s.start()else s.stop()};override fun onMediaMetadataChanged(m:androidx.media3.common.MediaMetadata){m.title?.toString()?.let{findViewById<TextView>(R.id.meta).text=it}}})},ContextCompat.getMainExecutor(this))
b.setOnClickListener{val p=c?:return@setOnClickListener;if(p.isPlaying)p.pause()else{val u=getSharedPreferences("radio",0).getString("Radio",RADIO)!!;p.setMediaItem(MediaItem.fromUri(u));p.prepare();p.play()}}
findViewById<SeekBar>(R.id.volume).setOnSeekBarChangeListener(object:SeekBar.OnSeekBarChangeListener{override fun onProgressChanged(x:SeekBar?,q:Int,z:Boolean){if(z)c?.volume=q/100f};override fun onStartTrackingTouch(x:SeekBar?){ };override fun onStopTrackingTouch(x:SeekBar?){}})
findViewById<Button>(R.id.videoBtn).setOnClickListener{startActivity(Intent(this,VideoActivity::class.java))};findViewById<Button>(R.id.settings).setOnClickListener{startActivity(Intent(this,SettingsActivity::class.java))}}
override fun onDestroy(){MediaController.releaseFuture(f);super.onDestroy()}}