name: Compilar Radio App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Forzar Gradle 8.7 sin usar caché de GitHub
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.7'
          cache-disabled: true

      - name: Compilar APK
        run: gradle assembleDebug

      - name: Subir APK para descargar
        uses: actions/upload-artifact@v4
        with:
          name: Radio-App-APK
          path: app/build/outputs/apk/debug/app-debug.apk
